version: "3.8"

services:
  redis:
    image: redis:alpine
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.prod
  web:
    build:
      context: ./project
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - env.prod
    depends_on:
      - db
      - redis
  celery:
    build: ./project
    command: celery -A core worker -l info
    volumes:
      - ./project/:/usr/src/app/
    env_file:
      - env.prod
    depends_on:
      - db
      - redis
  celery-beat:
    build: ./project
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./project/:/usr/src/app/
    env_file:
      - env.prod
    depends_on:
      - db
      - redis
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
