# Generated by Django 3.2.4 on 2021-10-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211020_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': '-created_at', 'ordering': ['-created_at'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed_date',
        ),
        migrations.AddField(
            model_name='order',
            name='binance_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Id Binance'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='order',
            name='side',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Side'),
        ),
        migrations.AddField(
            model_name='order',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Symbol'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
