# Generated by Django 3.2.4 on 2021-10-22 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211022_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True, verbose_name='Symbol')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-added'],
                'get_latest_by': '-added',
            },
        ),
    ]
