# Generated by Django 3.2.4 on 2021-10-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('SL', 'Stop Loss'), ('TP', 'Take Profit')], default='TP', max_length=2, verbose_name='Type'),
        ),
    ]
